name: Minimal Action Implementation

on: 
  pull_request:
    types: [opened, synchronize]
  push: 
    branches:
      - main
jobs: 
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable #specifies a the latest rust version to install
          override: true #override the default toolchain for the job
          
      - name: Build the project
        run: cargo build --release

      - name: print
        run: ./target/debug/fibbot ${{ github.even.inputs.input1 }} ${{ github.even.inputs.input2 }}
        
      # - name: Confirmation in logs
        # run: |
        #   if grep -q "Hello, world" $GITHUB_ENV; then
        #     echo "Hello, world' found in logs ! "  
        #   else 
        #     echo "'Hello world' not found in logs"
        #     exit 1
        #   fi
